### ISSUE TITLE
system id conflicts with another sentiment system I'm testing on Foundry

### ISSUE THREAD

**Issue by Epsi22** [tomlaflin/sentiment#3]
Is it possible to change the ID to something more descriptive? There is another sentiment system on github for Foundry with the same ID. 
I would like to have both sentiment systems installed at the same time so I can more easily compare which we're going to use for an upcoming game (and also playtest).

The pre-existing sentiment system it's conflicting with is this one here: https://github.com/djc6460/sentiment

**Comment by tomlaflin** [comment]
Annoyingly, I think "sentiment" is the correct system name and ID for both of our projects in a vacuum. We could change them to something like sentiment-arim and sentiment-aurus, but neither of us would want to release with those names. It doesn't feel like the right solution to check in name changes to the repo if they're only being made to facilitate a hypothetical side-by-side install with another project.

That being said, I recognize that this is a real scenario. I also want to have Aurus' system coexist on my computer so that I can compare and poke at the code. What I've done is to locally rename his system folder to sentiment-aurus, change the name and ID to sentiment-aurus in his system.json, and do a Find in Files to change all places in the code where the path "systems/sentiment" is specified to "systems/sentiment-aurus" instead. With that, I was able to have both systems coexist and create a world using his system with everything seemingly working fine.
